name: test123
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^3.0.0
  cloud_firestore: ^1.0.0
  equatable: ^2.0.0
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  flutter_bloc: ^7.0.0
  google_sign_in: ^4.5.9
  http: ^0.13.0
  intl: null
  qr_flutter: ^3.2.0
  rxdart: ^0.26.0
  table_calendar: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
